AFC Timing support
lnls-dig/uhal pull request #19
Opened 2023-06-14 17:27 UTC by ericonr

2023-07-12 19:27 UTC, augustofg requested changes

2023-07-12 19:27 UTC, augustofg commented on modules/afc_timing.cc
> +bool Controller::set_freq(double freq, struct clock &clock)
I think that this method should have an optional argument for the internal crystal frequency to be possible to use the calibrated value in the future.

2023-07-12 19:54 UTC, ericonr commented on modules/afc_timing.cc
> +bool Controller::set_freq(double freq, struct clock &clock)
If we start exposing the internal crystal frequency (by reading the rfreq registers after resetting the oscillator), wouldn't it make sense to always take it into account? I think it would involve a bigger API change, in that case.

2023-07-13 17:04 UTC, augustofg commented on modules/afc_timing.cc
> +bool Controller::set_freq(double freq, struct clock &clock)
So you prefer to use private variables of the `Controller` class to store the initial state of the Si57x clock generator chip? That is ok for me.

We should have a dedicated wishbone core for controlling Si57x devices in the future instead of exposing it in the LNLS_AFC_TIMING core, the BPM also has a software configurable Si57x in the FMC_250 ADC boards, but it is exposed at the I2C level I believe.

2023-07-17 12:53 UTC, ericonr commented on modules/afc_timing.cc
> +bool Controller::set_freq(double freq, struct clock &clock)
> So you prefer to use private variables of the Controller class to store the initial state of the Si57x clock generator chip? That is ok for me.

Indeed!

> We should have a dedicated wishbone core for controlling Si57x devices in the future instead of exposing it in the LNLS_AFC_TIMING core, the BPM also has a software configurable Si57x in the FMC_250 ADC boards, but it is exposed at the I2C level I believe.

Yeah, that would be ideal. We can workshop its ABI once we start reworking the timing gateware, I suppose? Unless configuring the BPM ones is necessary as well...

2023-07-24 19:30 UTC, merged