decode-reg: check if build_info exists in quiet mode.
lnls-dig/uhal pull request #48
Opened 2024-08-19 17:04 UTC by henriquesimoes

In an inconsistent link state, it is occasionally possible to open the resource file for a given board, even though it does not correctly report its synthesis information. In this situation, build_info will be empty and a segmentation fault will probably happen in `puts`. Avoid crashing in such cases by not assuming a value will always exist.

2024-08-29 17:54 UTC, ericonr requested changes

2024-08-29 17:54 UTC, ericonr commented on app/decode-reg.cc
> +        if (args.is_used("-q") && !build_info.empty())
We should probably still quit with an error and print something to `stderr`, no?

2024-08-29 18:19 UTC, henriquesimoes commented on app/decode-reg.cc
> +        if (args.is_used("-q") && !build_info.empty())
I considered that, but did not know what was "success" definition for that command. Just followed the behavior from non-quiet mode.

2024-08-29 18:24 UTC, ericonr commented on app/decode-reg.cc
> +        if (args.is_used("-q") && !build_info.empty())
We should fix non-quiet mode as well, then.
I didn't pay as much attention to the error codes here as I should have

2024-09-06 18:11 UTC, ericonr commented on app/decode-reg.cc
> +        if (args.is_used("-q") && !build_info.empty())
Augusto just complained about this, so fixing it now.

2024-09-06 21:13 UTC, henriquesimoes commented on app/decode-reg.cc
> +        if (args.is_used("-q") && !build_info.empty())
Okay. Feel free to take my commit as a partial fix, or simply to write down directly a special case for exiting sooner with a proper error message.

2024-09-06 21:56 UTC, ericonr commented on app/decode-reg.cc
> +        if (args.is_used("-q") && !build_info.empty())
Let me know what you think :)

2024-09-09 16:08 UTC, henriquesimoes commented on app/decode-reg.cc
> +        if (args.is_used("-q") && !build_info.empty())
That's nice. Thanks for complementing the message. I didn't look deep in the code to better describe it.

2024-09-10 14:22 UTC, ericonr approved these changes

2024-09-10 14:22 UTC, merged