Remove booster dependency
lnls-dig/uhal pull request #49
Opened 2024-09-06 18:09 UTC by ericonr

2024-09-06 18:09 UTC, ericonr commented
@henriquesimoes
@gustavosr8

2024-09-06 19:27 UTC, gustavosr8 commented on util/decoders.cc
> +        hash_u ^= hash_t + 0x9e3779b9 + (hash_u<<6) + (hash_u>>2);
Where did this `0x9e3779b9` value comes from?

2024-09-06 19:40 UTC, gustavosr8 requested changes

2024-09-06 19:40 UTC, gustavosr8 commented on util/decoders.cc
> +        return hash_t;
Shouldn't it be `hash_u` to be returned?

2024-09-06 21:26 UTC, ericonr commented on util/decoders.cc
> +        hash_u ^= hash_t + 0x9e3779b9 + (hash_u<<6) + (hash_u>>2);
It's the magic value used by boost themselves: https://stackoverflow.com/questions/35985960/c-why-is-boosthash-combine-the-best-way-to-combine-hash-values

2024-09-06 21:26 UTC, ericonr commented on util/decoders.cc
> +        return hash_t;
Indeed!!
Thanks :)

I had changed it in the calculation, but forgot about the result

2024-09-09 11:19 UTC, gustavosr8 commented on util/decoders.cc
> +        hash_u ^= hash_t + 0x9e3779b9 + (hash_u<<6) + (hash_u>>2);
Do you mind to mention it in the commit message? Magic numbers can easily become the reason for a misunderstanding or doubt, IMHO.

2024-09-09 14:23 UTC, ericonr commented on util/decoders.cc
> +        hash_u ^= hash_t + 0x9e3779b9 + (hash_u<<6) + (hash_u>>2);
Done >:)

2024-09-09 14:37 UTC, henriquesimoes approved these changes

2024-09-10 14:21 UTC, merged